### ISSUE TITLE
Invalid response code on template instances GET

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-resource-server#31]
Internal server instead of 401/403.

e.g/.

curl -X GET --header "Authorization: apiKey a3beee754f96fb2f1b137c584bcabccb35ba8aa02307fc56e30a681b07ce0e36" --header 'Accept: application/json' 'https://resource.metadatacenter.net/template-instances/https%3A%2F%2Frepo.metadatacenter.net%2Ftemplate-instances%2Fd4f1059e-8e27-4166-902f-be064f49d51c'

**Comment by martinjoconnor** [comment]
See also: https://github.com/metadatacenter/cedar-project/issues/338 (REST API cleanup)

**Comment by egyedia** [comment]
The endpoint currently returns 403 Forbidden, I think that is the expected behavior. I am closing this.
