### ISSUE TITLE
Search fields based on values

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-resource-server#59]
Allow users to search fields based on the possible values of a field. 

Significant design work required here for controlled term value since they are stored in BioPortal (and can dynamically change) so are not indexed.

Relevant for CDE work since caDSR form builders often search for relevant CDEs by the looking for values in the value sets associated with CDEs.

**Comment by martinjoconnor** [comment]
Will depend on possible future caDSR work.

**Comment by luz6** [comment]
The caveat is that the search will be based on what the "value"'s semantic context, i.e., if value is "1" for "male", the search results should be all gender/sex related CDEs to be shown after the search is executed.

**Comment by graybeal** [comment]
@luz6 That is another level of sophistication. Our basic implementation would let you search for all cases with values matching either a string ("1", "M") or a concept (one specific URI). I think many CDE users would be searching for a specific CDE with that non-semantic (that is, not mapped) target in mind.

In your use case, you would like the system to recognize the meaning of the person's search term. So, presumably they would specify that meaning with a concept IRI, not simply a label. Then the system needs to have (access to) mapping across all the CDE values, whether from value sets, ontologies, or even local codes (disconnected from any unique identifier)? Is that capability implemented in any CDE tool, or is the mapping information already available somewhere?

**Comment by luz6** [comment]
@Graybeal I think the mapping information is somewhere.  Can you confirm this with Denise? Since there are so many CDEs, search and filtering CDEs is one task identified to be improved - Clarifying and confirming the requirement will help better LOE.

**Comment by warzeld** [comment]
There is already a concept code associated with each value in the CDE’s value domain that serves as the “mapping” between the meaning of each value.  If one searched across all Permissible Values with the concept code, one could find all PVs with the same meaning, and thus all Value Domains with PVs that have the same meaning, and all CDEs containing that PV.  Hope that makes sense.

**Comment by cedaradmin** [comment]
Will be addressed by #70.

**Comment by martinjoconnor** [comment]
Erroneously closed with suggestion that task #70 replaced it. Now in Phase IV of CDE work.

**Comment by martinjoconnor** [comment]
Completed as part of Phase IV of CDE work.
