### ISSUE TITLE
Instance validation assertion is not yet implemented

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-resource-server#66]
The resource server does not check if the posted instance is valid or not.

Needs https://github.com/metadatacenter/cedar-model-validation-library/issues/126

**Comment by johardi** [comment]
So, I have a dilemma here:

1. The instance validator requires "@id" not null
2. The editor will POST a newly created metadata instance with `"@id": null`

==> Thus, the server will never accept posted metadata if we enable the validator.

Is it possible to send a dummy "@id" just to avoid the null ID so the validator can perform its task?

**Comment by martinjoconnor** [comment]
You mean the @id of the instance?

The instance validator should allow both an @id with a value of null and an @id with a URI value.

The @id is generated by the server so the editor can pass a null identifier on first instance POST - which will then get generated by the server.

**Comment by martinjoconnor** [comment]
FYI, this is the current behaviour of the template, element and field POST calls. Or should be.

**Comment by johardi** [comment]
Thanks, @martinjoconnor for the comment! I'll update the model to allow null value in the @id field, for metadata instances.

**Comment by johardi** [comment]
needs https://github.com/metadatacenter/cedar-template-editor/issues/858
