### ISSUE TITLE
Prototype field-based search backend

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-resource-server#70]
Develop search indices to allow field-based search and associated REST calls.

Should be able to search for artifacts based on field names and values. 

May also support URI- and synonym-based search.

**Comment by marcosmro** [comment]
I've created a document in our shared "CEDAR-NLM collaboration" folder to document the NLM's search requirements and describe the new search capabilities at different levels: general architecture, query syntax, API, and Elasticsearch. Find it here (still in progress): https://docs.google.com/document/d/1w3B48R6FnXO7oiIHfmG4eC7UdW-149UYQ8vLspOCAPU/edit#heading=h.h3hkgj1umnlc

**Comment by martinjoconnor** [comment]
Summary of current functionality here:

[https://app.zenhub.com/files/54140143/1d23036d-3e4c-40a8-91eb-42610a9c93b3/download](https://app.zenhub.com/files/54140143/1d23036d-3e4c-40a8-91eb-42610a9c93b3/download)

**Comment by martinjoconnor** [comment]
Summary of current functionality here:

[Search query syntax.pdf](https://github.com/metadatacenter/cedar-resource-server/files/3184805/Search.query.syntax.pdf)
