### ISSUE TITLE
Search for instances by templateId

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-resource-server#9]

**Comment by martinjoconnor** [comment]
Would like to discuss if this is need for 0.8 or can wait until 1.0.

**Comment by graybeal** [comment]
Suggest it could be a 'just after 0.8' test case -- I am imagining there will be users (including we of the extended CEDAR team) that want to know who's using their template, both for social reasons and to be able to notify them when the template has to change.

**Comment by martinjoconnor** [comment]
After today's BioCADDIE discussion, this should be in 0.8. They will need to pull instances of their particular template on a regular basis.

Would be nice to have a time parameter too so that, for example, user can get all instances created/updated in last day.

**Comment by martinjoconnor** [comment]
The 'all instances created/updated in last day' part of this is gravy and should only be done it is absolutely trivial. More important to get core feature working. Both LINCS and BioCADDIE groups would like this call.

**Comment by marcosmro** [comment]
Done. Example of curl command:
`curl -X GET -H "Content-Type: application/json" -H "Authorization: apiKey <your_api_key>" 'https://resource.staging.metadatacenter.net/search?template_id=<template_id>'`
